name = int(input("Enter a year"))
name2 = input("Enter a name")
name3 = input ("Enter a noun")
name4 = input("Enter a noun")
name5 = input("Enter a noun")
name6 = input("Enter an adjective")
name7 = input("Enter a body part")
name8 = input("Enter a noun")
name9 = input("Enter a noun")
name10 = input("Enter a verb")
name11 = input("Enter a noun")
name12 = input("Enter a verb")
name13 = input("Enter an adjective")
name14 = input("Enter an adjective")

print("On June of %d, %s, who was the CEO of %s introduced the revolutionary %s." % (name,name2,name3,name4))
print("It has %s gestures, being able to have a touch screen was %s It Works like Magic they said." % (name5, name6 ))
print("Using your %s instead of a keyboard or stylus made it extra special than the average %s like a %s." % (name7,name8,name9))
print("You just %s whatever you wanted to go on." % name10)
print("To get on the %s, he showed the users that you just %s to unlock instead of using a %s, %s." % (name11, name12, name13, name14))